### ISSUE TITLE
Random network error

### ISSUE THREAD

**Issue by MAXOUXAX** [MAXOUXAX/StatsRoyaleRefresher#1]
```python
2022-02-01 20:23:29,817 [MainThread  ] [ERROR]  HTTPSConnectionPool(host='statsroyale.com', port=443): Max retries exceeded with url: /profile/CGU8CVRRY/refresh (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffae3782b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
Traceback (most recent call last):
  File "/home/container/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/container/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/container/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/container/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/container/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/container/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/home/container/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/home/container/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0xffffae3782b0>: Failed to establish a new connection: [Errno 101] Network is unreachable
```

**Comment by MAXOUXAX** [comment]
Seems like 2865abec031e4dfa0e6419595fcafef0798c4ed3 fixed the issue!
